name: Deploy todolist application

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
      - name: Build docker image
        run: docker build -t clanar/todolist .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to docker hub
        run: docker push clanar/todolist:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull clanar/todolist:latest
      - name: Delete old container
        run: docker rm -f todolist-container || true # Ignore error if container does not exist
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name todolist-container clanar/todolist
